#include "__cf_nmm2DFullBody.h"
#ifndef RTW_HEADER_nmm2DFullBody_acc_types_h_
#define RTW_HEADER_nmm2DFullBody_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_GroundFrictionModel_nmm2DFullBody_T_
P_GroundFrictionModel_nmm2DFullBody_T ; typedef struct
P_LeftForcePlate_nmm2DFullBody_T_ P_LeftForcePlate_nmm2DFullBody_T ; typedef
struct P_StancePhase_nmm2DFullBody_T_ P_StancePhase_nmm2DFullBody_T ; typedef
struct P_SwingPhase_nmm2DFullBody_T_ P_SwingPhase_nmm2DFullBody_T ; typedef
struct P_StancePhase_nmm2DFullBody_j_T_ P_StancePhase_nmm2DFullBody_j_T ;
typedef struct P_StancePhase_nmm2DFullBody_d_T_
P_StancePhase_nmm2DFullBody_d_T ; typedef struct
P_SwingPhase_nmm2DFullBody_i_T_ P_SwingPhase_nmm2DFullBody_i_T ; typedef
struct P_StancePhase_nmm2DFullBody_di_T_ P_StancePhase_nmm2DFullBody_di_T ;
typedef struct P_SwingPhase_nmm2DFullBody_p_T_ P_SwingPhase_nmm2DFullBody_p_T
; typedef struct P_StancePhase_nmm2DFullBody_e_T_
P_StancePhase_nmm2DFullBody_e_T ; typedef struct P_nmm2DFullBody_T_
P_nmm2DFullBody_T ;
#endif
